[package]
name = "axum-restful"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6"
async-trait = "0.1.64"
sea-orm = { version = "0.11", features = ["macros", "sqlx-postgres", "runtime-tokio-rustls"] }
log = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[[example]]
name = "demo"
path = "examples/demo/src/main.rs"