[package]
name = "full"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum-restful = { path = "../../" }
axum = "0.6"
tokio = { version = "1", features = ["full"]}
